# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('etsi-impl-example', ['etsi-impl'])
    obj.source = 'etsi-impl-example.cc'
    
    obj = bld.create_ns3_program('etsi', ['etsi-impl'])
    obj.source = 'etsi_first.cc'
    obj.cflags=['-fPIC']
    
    obj = bld.create_ns3_program('ibrp', ['etsi-impl'])
    obj.source = 'ibrp.cc'
    obj.cflags=['-fPIC']
    

